spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: com.dissonance.itit.config.MariaDBFullTextDialect
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

jwt:
  token:
    secret-key: ${JWT_SECRET}

logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    s3:
      bucket: itit-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}